CC = gcc
CFLAGS = -Wall -Wextra

all: main.exe

main.exe: field_math.o ec_crypto.o main.o
	$(CC) $(CFLAGS) field_math.o ec_crypto.o main.o -o main.exe

field_math.o: field_math.c field_math.h
	$(CC) $(CFLAGS) -c field_math.c

ec_crypto.o: ec_crypto.c field_math.h
	$(CC) $(CFLAGS) -c ec_crypto.c

main.o: main.c field_math.h
	$(CC) $(CFLAGS) -c main.c

clean:
	rm -f *.o main.exe
